---
title: Promise
date: 2017-7-3 14:29:18
tags: [javascript,es6,unfinished]
layout: post
---

### 含义

`Promise`是异步编程的一种解决方案,相比较传统的回调函数和事件更合理,功能更强大.
`Promise`,本质上就是一个容器,里面保存着某个未来才会结束的事件(常是一个异步操作).语法上,`Promise`是一个对象,可以获取异步操作的消息.

### 特点

- **对象的状态不受外界影响**.`Promise`对象有三种状态,`pending`(进行中),`resolved`(已完成),`rejected`(已失败).
- **一旦状态改变，就不会再变.**`Promise`在状态切换过程中,是永久的,一旦状态改变了,任何时候去获取该状态是不会变的.也是会立即得到该结果.

### `Promise`实例

```js
var promise = new Promise((resolve,reject)=>{
  if(/*异步操作*/){
    resolve(value);
  }else{
    reject(error);
  }
});

```

`Promise`实例生成后,可以用`then`方法分别指定`resolved`和`rejected`状态的回调:

```js
promise.then(value=>{
    //success
},error=>{
    //failure
});
```

`then`方法结束两个参数,第一个`resolved`调用,第二个`rejected`调用,其中第二个参数不是必须的.

```js
//简单实例
let timeout = function(ms){
    return new Promise((resolve,reject)=>{
        setTimeout(resolve,ms,'run over');
    });
}

timeout(1000).then(value=>{
    console.log(value);
})

//图片加载
let afterImageLoaded = function(url){
    return new Promise((resolve,reject)=>{
        let image = new Image();
        image.onload = function(){
            resolve(image.src);
        }
        
        image.onerror = function(){
            reject(new Error('cannot load image through by url:'+ url));
        }
        
        image.src = url;
    });
}

afterImageLoaded(`http://oritfw5nq.bkt.clouddn.com/wall-303.jpg`).then(value=>{
    console.log(value)
},error=>{
    console.error(error);
});
```

> https://jsbin.com/yepotuc/edit?js,console

### `Promise.prototype.then()`

`then`方法的作用是为`Promise`实例添加状态改变时的回调函数.

`then`方法返回的是一个新的`Promise`实例,因此可以采用链式的写法.

### `Promise.prototype.catch()`

> `Promise.prototype.catch`方法是`.then(null, rejection)`的别名，用于指定发生错误时的回调函数。

相比较而言,`reject`的作用就是向外抛出错误

如果Promise状态已经变成Resolved，再抛出错误是无效的。

```js
var promise = new Promise(function(resolve, reject) {
  resolve('ok');
  throw new Error('test');
});
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) });
// ok
```

上面代码中，`Promise`在`resolve`语句后面，再抛出错误，不会被捕获，等于没有抛出。因为`Promise`的状态一旦改变，就永久保持该状态，不会再变了。

`Promise`对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个`catch`语句捕获。

### `Promise.all()`

> `Promise.all`方法用于将多个 `Promise` 实例，包装成一个新的 `Promise` 实例。

```js
var p = Promise.all([p1, p2, p3]);
```


### `Promise.race()`

> `Promise.race`方法同样是将多个Promise实例,包装成一个新的Promise实例

```js
var p = Promise.race([p1,p2,p3]);
```